version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: betalent_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: betalent_payments
      MYSQL_USER: betalent
      MYSQL_PASSWORD: betalent
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  gateways:
    image: matheusprotzen/gateways-mock
    container_name: betalent_gateways
    ports:
      - "3001:3001"
      - "3002:3002"

volumes:
  mysql_data: